apiVersion: v1
kind: Service
metadata:
       name: javawebappsvc
spec:
      type: LoadBalencer
      selector: 
              app: javawebapp
      ports:
      - port: 80
        targetPort: 8080